[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]

# Compilation
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 750
via_ir = false

[fuzz]
runs = 256

[fmt]
line_length = 80
int_types = "short"
number_underscore = "thousands"
ignore = ['src/generated/*', 'src/modules/fundingManager/bondingCurveFundingManager/formula/*']

[rpc_endpoints]
anvil = "http://localhost:8545"
optimism-sepolia = "https://inverter.web3no.de/main/evm/11155420"
sepolia = "https://inverter.web3no.de/main/evm/11155111"
polygon = "https://inverter.web3no.de/main/evm/137"

[etherscan]
optimism-sepolia = { key = "${ETHERSCAN_OPTIMISM_KEY}", chain = 11155420 }
sepolia = { key = "${ETHERSCAN_KEY}", chain = 11155111 }
polygon = { key = "${ETHERSCAN_POLYGON_KEY}", chain = 137 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
