name: Lint

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - "*"

env:
    FOUNDRY_PROFILE: ci

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Check formatting
              run: forge fmt --check
