name: Size Check
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: make install

      - name: Verify contract sizes
        run: make check-size
